version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: ./frontend

  backend:
    image: backend
    ports:
      - "3001:3001"
    build:
      dockerfile: Dockerfile
      context: ./backend
