version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - "80:80"
    build:
      dockerfile: Dockerfile
      context: ./frontend
  backend:
    image: backend
    ports:
      - "3001:3001"
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
        - "db"
    command: ["wait-for-it", "db:27017", "--", "node", "server.js"]
  db:
    image: mongo:4.2.0
    volumes:
      - "mongodata:/data/db"
    ports:
      - 27017:27017
    command: mongod --noauth
    
volumes:
  mongodata:    
  
